import { ThemeProperty } from '@app/core/models/theme.model';
import * as MISCELLANY_IMAGES from '../miscellany/images';
import { ICONS_CSS_VAR, IMAGES_CSS_VAR } from '../miscellany/images';

export const IMAGES: ThemeProperty = {
  /***
    IMAGES
  **/
  // BACKGROUNDS
  [IMAGES_CSS_VAR.BACKGROUND]: `url(${MISCELLANY_IMAGES.IMAGE_BACKGROUND})`,
  // LOGOS
  [IMAGES_CSS_VAR.LOGO]: `url(${MISCELLANY_IMAGES.IMAGE_LOGO})`,
  // FIGURES
  [IMAGES_CSS_VAR.FIGURE_HERO]: `url(${MISCELLANY_IMAGES.IMAGE_FIGURE_HERO})`,
  // SECTIONS
  [IMAGES_CSS_VAR.SECTION_CODE_HERO]: `url(${MISCELLANY_IMAGES.IMAGE_SECTION_CODE_HERO})`,
  // TOOLS
  [IMAGES_CSS_VAR.TOOL_ANGULAR]: `url(${MISCELLANY_IMAGES.IMAGE_TOOL_ANGULAR})`,
  [IMAGES_CSS_VAR.TOOL_NGRX]: `url(${MISCELLANY_IMAGES.IMAGE_TOOL_NGRX})`,
  [IMAGES_CSS_VAR.TOOL_REACT]: `url(${MISCELLANY_IMAGES.IMAGE_TOOL_REACT})`,
  [IMAGES_CSS_VAR.TOOL_GIT]: `url(${MISCELLANY_IMAGES.IMAGE_TOOL_GIT})`,
  [IMAGES_CSS_VAR.TOOL_CSHARP]: `url(${MISCELLANY_IMAGES.IMAGE_TOOL_CSHARP})`,
  [IMAGES_CSS_VAR.TOOL_FIGMA]: `url(${MISCELLANY_IMAGES.IMAGE_TOOL_FIGMA})`,
  [IMAGES_CSS_VAR.TOOL_ATLASSIAN]: `url(${MISCELLANY_IMAGES.IMAGE_TOOL_ATLASSIAN})`,
  /***
    ICONS
  **/
  // GENERAL
  [ICONS_CSS_VAR.CLOSE]: `url(${MISCELLANY_IMAGES.ICON_CLOSE})`,
};
