import { ThemeProperty } from '@app/core/models/theme.model';
import * as MISCELLANY_IMAGES from '../miscellany/images';
import { ICONS_CSS_VAR, IMAGES_CSS_VAR } from '../miscellany/images';

export const IMAGES: ThemeProperty = {
  /***
    IMAGES
  **/
  // BACKGROUNDS
  [IMAGES_CSS_VAR.BACKGROUND_LOGIN]: `url(${MISCELLANY_IMAGES.IMAGE_BACKGROUND_LOGIN})`,
  [IMAGES_CSS_VAR.BACKGROUND_CLOTHES]: `url(${MISCELLANY_IMAGES.IMAGE_BACKGROUND_CLOTHES})`,
  [IMAGES_CSS_VAR.BACKGROUND_AGGREGATOR_ACCOUNT]: `url(${MISCELLANY_IMAGES.IMAGE_BACKGROUND_AGGREGATOR_ACCOUNT})`,
  // LOGOS
  [IMAGES_CSS_VAR.LOGO_MO]: `url(${MISCELLANY_IMAGES.IMAGE_LOGO_MO})`,
  [IMAGES_CSS_VAR.LOGO_BNPL]: `url(${MISCELLANY_IMAGES.IMAGE_LOGO_BNPL})`,
  [IMAGES_CSS_VAR.LOGO_BNPL_WHITE]: `url(${MISCELLANY_IMAGES.IMAGE_LOGO_BNPL_WHITE})`,
  [IMAGES_CSS_VAR.LOGO_POWER_BY_MO]: `url(${MISCELLANY_IMAGES.IMAGE_LOGO_POWER_BY_MO})`,
  /***
    ICONS
  **/
  // GENERAL
  [ICONS_CSS_VAR.CHECK_SUCCESS]: `url(${MISCELLANY_IMAGES.ICON_CHECK_SUCCESS})`,
  [ICONS_CSS_VAR.WARNING]: `url(${MISCELLANY_IMAGES.ICON_WARNING})`,
  [ICONS_CSS_VAR.SELECT_ARROW_DOWN]: `url(${MISCELLANY_IMAGES.ICON_SELECT_ARROW_DOWN})`,
  [ICONS_CSS_VAR.CLOSE]: `url(${MISCELLANY_IMAGES.ICON_CLOSE})`,
  [ICONS_CSS_VAR.TAG_CIRCLE]: `url(${MISCELLANY_IMAGES.ICON_TAG_CIRCLE})`,
  [ICONS_CSS_VAR.EMPTY]: `url(${MISCELLANY_IMAGES.ICON_EMPTY})`,
  [ICONS_CSS_VAR.FILTER]: `url(${MISCELLANY_IMAGES.ICON_FILTER})`,
  [ICONS_CSS_VAR.DUPLICATE]: `url(${MISCELLANY_IMAGES.ICON_DUPLICATE})`,
  // MENU
  [ICONS_CSS_VAR.MENU_LOGO_BNPL]: `url(${MISCELLANY_IMAGES.ICON_MENU_LOGO_BNPL})`,
  [ICONS_CSS_VAR.MENU_ARROW_LEFT]: `url(${MISCELLANY_IMAGES.ICON_MENU_ARROW_LEFT})`,
  [ICONS_CSS_VAR.MENU_ARROW_RIGHT]: `url(${MISCELLANY_IMAGES.ICON_MENU_ARROW_RIGHT})`,
  [ICONS_CSS_VAR.MENU_BURGER]: `url(${MISCELLANY_IMAGES.ICON_MENU_BURGER})`,
  // MENU - ITEMS
  [ICONS_CSS_VAR.MENU_AGGREGATOR_ACCOUNT]: `url(${MISCELLANY_IMAGES.ICON_MENU_AGGREGATOR_ACCOUNT})`,
  [ICONS_CSS_VAR.MENU_POINT_OF_SALE]: `url(${MISCELLANY_IMAGES.ICON_MENU_POINT_OF_SALE})`,
  [ICONS_CSS_VAR.MENU_ASSOCIATED_AGGREGATORS]: `url(${MISCELLANY_IMAGES.ICON_MENU_ASSOCIATED_AGGREGATORS})`,
  [ICONS_CSS_VAR.MENU_PURCHASE_MANAGER]: `url(${MISCELLANY_IMAGES.ICON_MENU_PURCHASE_MANAGER})`,
  [ICONS_CSS_VAR.MENU_SETTLEMENTS]: `url(${MISCELLANY_IMAGES.ICON_MENU_SETTLEMENTS})`,
  [ICONS_CSS_VAR.MENU_REPORTS]: `url(${MISCELLANY_IMAGES.ICON_MENU_REPORTS})`,
  // NAVBAR
  [ICONS_CSS_VAR.NAVBAR_SMILE_FACE]: `url(${MISCELLANY_IMAGES.ICON_NAVBAR_SMILE_FACE})`,
  // TABLE
  [ICONS_CSS_VAR.TABLE_SORT]: `url(${MISCELLANY_IMAGES.ICON_TABLE_SORT})`,
  [ICONS_CSS_VAR.TABLE_SORT_ASC]: `url(${MISCELLANY_IMAGES.ICON_TABLE_SORT_ASC})`,
  [ICONS_CSS_VAR.TABLE_SORT_DESC]: `url(${MISCELLANY_IMAGES.ICON_TABLE_SORT_DESC})`,
};
